name: Build Experimental (Alpha) Build

on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [ experimental ]

jobs:
  a50:
    name: Build Galaxy A50 (One UI)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2
      
    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install build-essential libelf-dev kernel-package bzip2 lib32stdc++6 libc6-dev-i386 git -y
      
    - name: Install Toolchain
      run: |
          set -eo pipefail
          git clone https://github.com/CruelKernel/aarch64-cruel-elf.git ${HOME}/toolchain
          mkdir -p ${HOME}/toolchain_arm32
          wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz --output-document=${HOME}/toolchain_arm32/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz
          tar -xvf ${HOME}/toolchain_arm32/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz -C ${HOME}/toolchain_arm32
        
    - name: Build Kernel
      run: |
          set -eo pipefail
          echo "  I: Building FreshCore CI $GITHUB_RUN_NUMBER"
          export KBUILD_BUILD_VERSION=$GITHUB_RUN_NUMBER
          ./build.sh a50 ci

    - name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50 Kernel Image (experimental-${{ github.run_number }})
        path: 'tools/package/others/boot.img'
        if-no-files-found: error

    - name: Upload config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy A50 Kernel Config (experimental-${{ github.run_number }})
        path: 'release/kernel_config_a50.txt'
        if-no-files-found: error
